### ISSUE TITLE
Spaghetti

### ISSUE THREAD

**Issue by numbertumbers** [Flatpak-Remix/website#2]
The website code could use some refactoring, I'm working on it right now, but I'm really not sure what I can do here. If I don't come back with the pull request, tell my family I love them.

**Comment by LearnLinuxTV** [comment]
Before you go too far, the site is kind of placeholder. At some point I'd like to redesign it in Hugo. But I'll still be thankful for any pull request you may submit.

**Comment by numbertumbers** [comment]
I think I might close this issue actually. I'm wasting my time.

**Comment by numbertumbers** [comment]
I'm closing this actually. I tried my hardest, but I can't fix this.

**Comment by LearnLinuxTV** [comment]
Thank you so much for trying, I really appreciate it. I think this is just going to need to be remade at some point.
